using Gui.Gameplay.Presenters.Cells;
using UnityEngine;
using UnityEngine.Serialization;

namespace Gui.ScriptableObjects
{
	[CreateAssetMenu(fileName = nameof(SudokuCellsSpawner), menuName = "Game/" + nameof(SudokuCellsSpawner))]
	public class SudokuCellsSpawner : ScriptableObject
	{
		[SerializeField] private SolverCellPresenter _solverCellPresenter;
		[SerializeField] private UserCellPresenter _userCellPresenter;

		public ICellPresenter SpawnCell(bool autoGeneratedCell, Transform container)
		{
			return autoGeneratedCell ? Instantiate(_solverCellPresenter, container) : Instantiate(_userCellPresenter, container);
		}
	}
}
